//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darpan
{
    public partial class Desh
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        // NEWLY ADDED DECLARATIONS:
        protected global::System.Web.UI.WebControls.LinkButton btnExploreStates;
        protected global::System.Web.UI.WebControls.LinkButton btnGetStateNews;
        protected global::System.Web.UI.WebControls.Panel pnlExploreStates;
        protected global::System.Web.UI.WebControls.Panel pnlGetStateNews;
        protected global::System.Web.UI.WebControls.Literal litSelectedStateNews; // For news section

        // Existing declarations
        protected global::System.Web.UI.WebControls.DropDownList ddlStates;
        protected global::System.Web.UI.WebControls.Literal litSelectedState;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Repeater rptStateInfo;
    }
}
