//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darpan
{
    public partial class Videsh
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        // NEWLY ADDED DECLARATIONS:
        protected global::System.Web.UI.WebControls.LinkButton btnExploreCountries;
        protected global::System.Web.UI.WebControls.LinkButton btnGetCountryNews;
        protected global::System.Web.UI.WebControls.Panel pnlExploreCountries;
        protected global::System.Web.UI.WebControls.Panel pnlGetCountryNews;
        protected global::System.Web.UI.WebControls.Literal litSelectedCountryNews; // For news section

        // Existing declarations
        protected global::System.Web.UI.WebControls.DropDownList ddlCountries;
        protected global::System.Web.UI.WebControls.Literal litSelectedCountry;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Repeater rptCountryInfo;
    }
}